fix maturin build error

diff --git a/.github/workflows/maturin.yaml b/.github/workflows/maturin.yaml
--- a/.github/workflows/maturin.yaml
+++ b/.github/workflows/maturin.yaml
@@ -10,18 +10,31 @@ on:
         default: 'latest'
 
 jobs:
-  build:
-    name: Build maturin ${{ matrix.platform }} wheel on ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [loongarch64-abi2.0]
-        platform: ["manylinux", "musllinux"]
+  check-wheel-exists:
+    name: Check if exists
+    runs-on: loongarch64-abi2.0
+    outputs:
+      version: ${{ steps.check.outputs.version }}
+      build_manylinux: ${{ steps.check.outputs.build_manylinux }}
+      build_musllinux: ${{ steps.check.outputs.build_musllinux }}
     steps:
-      - name: Check if exists
+      - name: Check if wheels exist
+        id: check
         run: |
           pkg=maturin
+
+          check_wheel() {
+            local tag=$1
+
+            if curl -Ls "${url}" | grep -q "${pkg}-${version}.*${tag}"; then
+              echo "build_${tag}=false" >> $GITHUB_OUTPUT
+              echo "${tag} wheel already exists."
+            else
+              echo "build_${tag}=true" >> $GITHUB_OUTPUT
+              echo "${tag} wheel not found, continue building."
+            fi
+
+          }
 
           if [[ "${{ github.event_name }}" == "schedule" ]]; then
             version="latest"
@@ -29,7 +42,6 @@ jobs:
             version="${{ github.event.inputs.version }}"
           fi
 
-          platform="${{ matrix.platform }}"
           url="https://lpypi.loongnix.cn/loongson/pypi/+simple/${pkg}/"
           upstream_url="https://pypi.org/pypi/${pkg}/json"
 
@@ -37,50 +49,113 @@ jobs:
             version="$(curl -s ${upstream_url} | jq -r '.info.version')"
           fi
 
-          if curl -s ${url} | grep -q ${pkg}-${version}-.*${platform}; then
-            echo "SKIP=true" >> $GITHUB_ENV
-            echo "${platform} wheels already exists."
-          else
-            echo "SKIP=false" >> $GITHUB_ENV
-            echo "${platform} wheels not found, continue building"
-          fi
+          echo "version=v${version}" >> $GITHUB_OUTPUT
 
-          echo "VERSION=${version}" >> $GITHUB_ENV
+          for tag in manylinux musllinux; do
+            check_wheel "$tag"
+          done
 
+  debug:
+    name: Debug outputs
+    needs: check-wheel-exists
+    runs-on: loongarch64-abi2.0
+    steps:
+      - run: |
+          echo "build_manylinux=${{ needs.check-wheel-exists.outputs.build_manylinux }}"
+          echo "build_musllinux=${{ needs.check-wheel-exists.outputs.build_musllinux }}"
+
+  download:
+    name: Download source
+    needs: check-wheel-exists
+    env:
+      version: ${{ needs.check-wheel-exists.outputs.version }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [loongarch64-abi2.0]
+    if: ${{ needs.check-wheel-exists.outputs.build_manylinux == 'true' || needs.check-wheel-exists.outputs.build_musllinux == 'true' }}
+    steps:
       - name: Clean workspace
-        if: ${{ env.SKIP != 'true' }}
-        run: |
-          safe-rm -rf * .*
+        run: safe-rm -rf * .*
 
       - name: Download source
-        if: ${{ env.SKIP != 'true' }}
-        uses: wxpppp/sources@main
+        uses: actions/checkout@v4
         with:
-          name: maturin
-          version: ${{ env.VERSION }}
+          repository: PyO3/maturin 
+          ref: ${{ env.version }}
+
+      - name: Patch source
+        run: |
+          curl -sL https://github.com/loong64/maturin/raw/refs/heads/main/patch-loong64.patch | patch -p1
+        
+  build:
+    name: Build maturin ${{ matrix.platform }} wheel on ${{ matrix.os }}
+    needs: [check-wheel-exists, download]
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - os: loongarch64-abi2.0
+            image: "lcr.loongnix.cn/pypa/manylinux_2_38_loongarch64"
+            target: "loongarch64-unknown-linux-gnu"
+            platform: "manylinux_2_38"
+          - os: loongarch64-abi2.0
+            image: "lcr.loongnix.cn/pypa/musllinux_1_2_loongarch64"
+            target: "loongarch64-unknown-linux-musl"
+            platform: "musllinux_1_2"
+    container:
+      image: ${{ matrix.image }}
+      env:
+        RUSTUP_HOME: /root/.rustup
+        CARGO_HOME: /root/.cargo
+        CARGO_PROFILE_RELEASE_LTO: "${{ matrix.platform.lto || 'fat' }}"
+        HTTPS_PROXY: ${{ secrets.PROXY_URL }}
+        SKIP: true
+    steps:
+      - name: Check if wheel exists
+        if: |
+          ${{ (matrix.platform == 'manylinux_2_38' && needs.check-wheel-exists.outputs.build_manylinux == 'true') || (matrix.platform  == 'musllinux_1_2' && needs.check-wheel-exists.outputs.build_musllinux == 'true') }}
+        run:
+          echo "SKIP=false" >> $GITHUB_ENV
+
+      - name: Setup rust-toolchain
+        if: ${{ env.SKIP != 'true' }}
+        run: |
+          curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal
 
       - name: Build wheel
         if: ${{ env.SKIP != 'true' }}
-        run: cibuildwheel
+        run: |
+          pipx install maturin
+          export PATH="/root/.cargo/bin:$PATH"
+          maturin build --release -b bin -o dist --target ${{ matrix.target }} --compatibility ${{ matrix.platform }} --features password-storage
         env:
           PIP_EXTRA_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
-          PIP_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"
-          CIBW_ARCHS: "loongarch64"
-          CIBW_BUILD: "*-${{ matrix.platform }}_loongarch64"
-          CIBW_SKIP: "cp37* cp38*"
-          CIBW_BEFORE_ALL_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
-          CIBW_ENVIRONMENT_LINUX: >
-            PATH="$HOME/.cargo/bin:$PATH"
-            HTTPS_PROXY=${{ secrets.PROXY_URL }}
-          CIBW_ENVIRONMENT_PASS_LINUX: >
-            PIP_INDEX_URL
-            PIP_EXTRA_INDEX_URL
 
-      - name: Upload wheels
-        if: ${{ env.SKIP != 'true' }}
+  upload:
+    name: Upload wheels
+    needs: [check-wheel-exists, build]
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [loongarch64-abi2.0]
+    env:
+      TWINE_USERNAME: ${{ secrets.INDEX_NAME  }}
+      TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}
+      build_manylinux: ${{ needs.check-wheel-exists.outputs.build_manylinux }}
+      build_musllinux: ${{ needs.check-wheel-exists.outputs.build_musllinux }}
+    steps:
+      - name: Upload manylinux wheel
+        if: ${{ env.build_manylinux == 'true' }}
         run: |
-          ls wheelhouse/*-${{ matrix.platform }}_*.whl || exit 1
-          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/*-${{ matrix.platform }}_*.whl
-        env:
-          TWINE_USERNAME: ${{ secrets.INDEX_NAME }}
-          TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}
+          ls dist/*-manylinux_*.whl || exit 1
+          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi dist/*-manylinux_*.whl
+
+      - name: Upload musllinux wheel
+        if: ${{ env.build_musllinux == 'true' }}
+        run: |
+          ls dist/*-musllinux_*.whl || exit 1
+          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi dist/*-musllinux_*.whl
